name: Generate sitemap

on:
  schedule:
    - cron: '0 3 * * *'  # 毎日朝3時（日本時間12時）に実行
  workflow_dispatch:     # 手動実行も可

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests feedparser

      - name: Run sitemap generator
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update sitemap"
          git push
