name: Update Blogger Sitemap

on:
  workflow_dispatch:  # 手動実行対応
  schedule:
    - cron: '0 3 * * *'  # 毎日日本時間12:00に実行（UTCで03:00）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Generate sitemap.xml
        run: python generate_sitemap.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap.xml [auto]" || echo "No changes to commit"

      - name: Push changes (force)
        run: git push origin main --force
