name: Update Blogger Sitemap

# トリガー：手動実行と毎日午前1時（UTC）に自動実行
on:
  workflow_dispatch:  # 手動実行用トリガー
  schedule:
    - cron: '0 1 * * *'  # 毎日午前1時（UTC）→ 日本時間で午前10時

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run sitemap generator
        run: python generate_sitemap.py

      - name: Commit and push sitemap.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap.xml [auto]" || echo "No changes to commit"
          git push
